### ISSUE TITLE
Socket reading issues with neo4j+s driver and 2.4.x series

### ISSUE THREAD

**Issue by killerbishop** [neo4j-php/neo4j-php-client#108]
**Describe the bug**
Upgrading to the latest version of this client causes AuraDB connections to fail using neo4j+s driver. Downgrading to version 2.3.9 of the package seems to fix the issue which also downgrades the bolt driver from 3.1.1 to 2.7.2. When running in the latest version, an exception is thrown:

```
PHP Fatal error:  Uncaught Bolt\error\ConnectException: Read error in D:\kille\git\userstitch\vendor\stefanak-michal\bolt\src\connection\StreamSocket.php:104
Stack trace:
#0 D:\kille\git\userstitch\vendor\stefanak-michal\bolt\src\Bolt.php(138): Bolt\connection\StreamSocket->read(4)
#1 D:\kille\git\userstitch\vendor\stefanak-michal\bolt\src\Bolt.php(123): Bolt\Bolt->unpackProtocolVersion()
#2 D:\kille\git\userstitch\vendor\stefanak-michal\bolt\src\Bolt.php(69): Bolt\Bolt->handshake()
#3 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\BoltFactory.php(68): Bolt\Bolt->build()
#4 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Bolt\BoltConnectionPool.php(114): Laudis\Neo4j\BoltFactory->build()
#5 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Bolt\BoltConnectionPool.php(88): Laudis\Neo4j\Bolt\BoltConnectionPool->getConnection(Object(Laudis\Neo4j\Common\Uri), Object(Laudis\Neo4j\Authentication\NoAuth), Object(Laudis\Neo4j\Databags\SessionConfiguration))
#6 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Neo4j\Neo4jConnectionPool.php(85): Laudis\Neo4j\Bolt\BoltConnectionPool->acquire(Object(Laudis\Neo4j\Common\Uri), Object(Laudis\Neo4j\Authentication\NoAuth), Object(Laudis\Neo4j\Databags\SessionConfiguration), Object(Laudis\Neo4j\Neo4j\RoutingTable), Object(Laudis\Neo4j\Common\Uri))
#7 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Bolt\Session.php(159): Laudis\Neo4j\Neo4j\Neo4jConnectionPool->acquire(Object(Laudis\Neo4j\Common\Uri), Object(Laudis\Neo4j\Authentication\NoAuth), Object(Laudis\Neo4j\Databags\SessionConfiguration))
#8 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Bolt\Session.php(147): Laudis\Neo4j\Bolt\Session->acquireConnection(Object(Laudis\Neo4j\Databags\TransactionConfiguration), Object(Laudis\Neo4j\Databags\SessionConfiguration))
#9 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Bolt\Session.php(85): Laudis\Neo4j\Bolt\Session->beginInstantTransaction(Object(Laudis\Neo4j\Databags\SessionConfiguration), Object(Laudis\Neo4j\Databags\TransactionConfiguration))
#10 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Client.php(77): Laudis\Neo4j\Bolt\Session->runStatements(Array, Object(Laudis\Neo4j\Databags\TransactionConfiguration))
#11 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Client.php(70): Laudis\Neo4j\Client->runStatements(Array, NULL)
#12 D:\kille\git\userstitch\vendor\laudis\neo4j-php-client\src\Client.php(65): Laudis\Neo4j\Client->runStatement(Object(Laudis\Neo4j\Databags\Statement), NULL)
#13 D:\kille\git\userstitch\scripts\test.php(20): Laudis\Neo4j\Client->run('MATCH (n)')
#14 {main}
  thrown in D:\kille\git\userstitch\vendor\stefanak-michal\bolt\src\connection\StreamSocket.php on line 104
```

**To Reproduce**
Basic code to reproduce failure:

```php
require_once __DIR__ . '/../vendor/autoload.php';

use Laudis\Neo4j\ClientBuilder;
use Laudis\Neo4j\Authentication\Authenticate;

$client = ClientBuilder::create()
    ->withDriver(
        'neo4j',
        'neo4j+s://' . $_ENV['NEO4J_DB'],
        Authenticate::basic($_ENV['NEO4J_USER'], $_ENV['NEO4J_PASS'])
    )
    ->withDefaultDriver('neo4j')
    ->build();

    $client->run('MATCH (n) RETURN n');
```

**Expected behavior**
It should run the client query instead of throwing an error.

**Desktop (please complete the following information):**
 - Library version: 4.4.1
 - Neo4j Version: aura
 - PHP version: 8.0.13
 - OS: Windows 10

**Comment by transistive** [comment]
Thank you for the detailed explanation! This has been fixed in version 2.4.2
