### ISSUE TITLE
Committed transactions may have their results discarded

### ISSUE THREAD

**Issue by transistive** [neo4j-php/neo4j-php-client#126]
**Describe the bug**
When a transaction get committed, the driver may still try and run discard on a connection in READY state.

**To Reproduce**
This issue is similar to https://github.com/neo4j-php/neo4j-php-client/issues/117
Run a query through a transaction, then commit, an error occurs indicating a failure on the DISCARD message
Steps:
1. Create client
2. Run a query through a transaction then commit
```php
$tsx = $client->beginTransaction();
$result = $tsx->run("MATCH (n:Node) SET n.testing = 'world' RETURN n");
$tsx->commit();
```
This error is produced
```
In V4.php line 94:
                                                                                                                                             
  Message 'DISCARD Map{qid -> Long(0), n -> Long(-1)}' cannot be handled by a session in the READY state. (Neo.ClientError.Request.Invalid) 
```
So I check the debug logs in neo4j and found this error
```
2022-03-16 17:34:35.029+0000 DEBUG [o.n.b.v.m.BoltResponseMessageWriterV3] Encoding a fatal failure message to send. Message: FAILURE Invalid Message 'DISCARD Map{qid -> Long(0), n -> Long(-1)}' cannot be handled by a session in the READY state.
2022-03-16 17:34:35.029+0000 ERROR [o.n.b.r.DefaultBoltConnection] Protocol breach detected in bolt session 'bolt-20'.
org.neo4j.bolt.runtime.BoltProtocolBreachFatality: Message 'DISCARD Map{qid -> Long(0), n -> Long(-1)}' cannot be handled by a session in the READY state.
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:159) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:102) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:93) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:156) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:252) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:187) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:177) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:257) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$3(ExecutorBoltScheduler.java:240) ~[neo4j-bolt-4.4.3.jar:4.4.3]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.69.Final.jar:4.1.69.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Expected behavior**
The result should become consumed before the commit happens.

**Additional context**
Taken from #124

**Comment by transistive** [comment]
closed by #131
