### ISSUE TITLE
Breaking change from 2.8.3

### ISSUE THREAD

**Issue by GinoPane** [neo4j-php/neo4j-php-client#169]
A minor version upgrade (2.8.2 - 2.8.3) introduced a breaking change

```
Fatal error: During inheritance of ArrayAccess: Uncaught Behat\Testwork\Call\Exception\CallErrorException: 8192: Return type of Laudis\Neo4j\Types\AbstractCypherObject::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /application/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherObject.php line 73 in /application/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:90
Stack trace:
#0 /application/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherObject.php(37): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleError(8192, 'Return type of ...', '/application/ve...', 73)
#1 /application/vendor/composer/ClassLoader.php(578): include('/application/ve...')
#2 /application/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/application/ve...')
#3 /application/vendor/laudis/neo4j-php-client/src/Databags/Statement.php(25): Composer\Autoload\ClassLoader->loadClass('Laudis\\Neo4j\\Ty...')
```

**Comment by transistive** [comment]
Thank you for the headsup. It is fixed in version 3.0.0
