### ISSUE TITLE
SSL Certificate problem when connecting to remote DB

### ISSUE THREAD

**Issue by sergio-nunez-meneses-davi** [neo4j-php/neo4j-php-client#54]
I have been trying to connect to a neo4j database, hosted in Azure , using `Laudis Neo4j PHP Client`. I have followed the steps described in the [documentation](https://github.com/neo4j-php/neo4j-php-client#laudis-neo4j-php-client) but got an exception.

Here's the code for connecting to the database:

```php
$this->client = ClientBuilder::create()
  ->withDriver('bolt',
               sprintf('%s://%s:%s@%s:7687', DB_PROTOCOLE, DB_USER, DB_PASSWORD, DB_HOST))
  ->build();
```

Here's the exception thrown: 

```html
<b>Fatal error</b>: Uncaught Bolt\error\ConnectException: Read error in
C:\xampp\htdocs\adt-api\vendor\stefanak-michal\bolt\src\connection\StreamSocket.php:102
Stack trace:
#0 C:\xampp\htdocs\adt-api\vendor\stefanak-michal\bolt\src\Bolt.php(161): Bolt\connection\StreamSocket-&gt;read(4)
#1 C:\xampp\htdocs\adt-api\vendor\stefanak-michal\bolt\src\Bolt.php(140): Bolt\Bolt-&gt;unpackProtocolVersion()
#2 C:\xampp\htdocs\adt-api\vendor\stefanak-michal\bolt\src\Bolt.php(214): Bolt\Bolt-&gt;handshake()
#3 C:\xampp\htdocs\adt-api\vendor\laudis\neo4j-php-client\src\Authentication\BasicAuth.php(47):
Bolt\Bolt-&gt;init('neo4j-php-clien...', 'user', 'pwd')
#4 C:\xampp\htdocs\adt-api\vendor\laudis\neo4j-php-client\src\Authentication\UrlAuth.php(41):
Laudis\Neo4j\Authentication\BasicAuth-&gt;authenticateBolt(Object(Bolt\Bolt), Object(Laudis\Neo4j\Common\Uri),
'neo4j-php-clien...')
#5 C:\xampp\htdocs\adt-api\vendor\laudis\neo4j-php-client\src\Bolt\Session.php(118):
Laudis\Neo4j\Authentication\UrlAuth-&gt;authenticateBolt(Object(Bolt\Bolt), Object(La in
<b>C:\xampp\htdocs\adt-api\vendor\laudis\neo4j-php-client\src\Bolt\Session.php</b> on line <b>129</b>
```

Exceptions #0 and #2 led me to inspect the `BoltConnectionPool` class, and found an issue on line 43. The condition `str_starts_with('s', $host)` tries to find an 's' in the host name, but my host name doesn't have any. Thus, the SSL certificate is never enabled. 
Replacing the variable `$host` by `$sslConfig` solved the problem.

```php
public function acquire(UriInterface $uri, AccessMode $mode): StreamSocket
{
    $host = $uri->getHost();
    $socket = new StreamSocket($host, $uri->getPort() ?? 7687);

    $scheme = $uri->getScheme();
    $explosion = explode('+', $scheme, 2);
    $sslConfig = $explosion[1] ?? '';

    // Replaced $host by $sslConfig, as my host doesn't start with an s (ex: neo4j.my-site.com)
    if (str_starts_with('s', $sslConfig)) {
        $this->enableSsl($host, $sslConfig, $socket);
    }

    return $socket;
}
```

I had forked the repository and submit a PR to fix the issue. I hope this might help others experiencing the same problem.

**Comment by transistive** [comment]
Hello Sergio!

Thank you very much for this! It looks I made a typo here and referred to the wrong variable. Thank you for submitting a PR!

The tests are running now. I will merge it and release version 2.0.1 afterwards as there are some other smaller bug fixes that are in there as well.

Have a good day,

Ghlen
