### ISSUE TITLE
Uncaught Bolt\error\ConnectException: Read error

### ISSUE THREAD

**Issue by jonathan-rowley** [neo4j-php/neo4j-php-client#83]
**Describe the bug**
This is an issue I have been having with the driver. I default to the neo4j driver which uses the Bolt protocol but sometimes I will get this error:

```
PHP Fatal error:  Uncaught Bolt\error\ConnectException: Read error in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:102
Stack trace:
#0 /vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(94): Bolt\connection\StreamSocket->read()
#1 /vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#2 /vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#3 /vendor/stefanak-michal/bolt/src/Bolt.php(274): Bolt\protocol\V4->pullAll()
#4 /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php(105): Bolt\Bolt->pullAll()
#5 /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php(54): Laudis\Neo4j\Bolt\BoltUnmanagedTransaction->runStatements()
#6 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(73): Laudis\Neo4j\Bolt\BoltUnmanagedTransaction->commit()
#7 /vendor/laudis/neo4j-php-client/src/Bolt/Ses in /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php on line 107

Fatal error: Uncaught Bolt\error\ConnectException: Read error in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:102
Stack trace:
#0 /vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(94): Bolt\connection\StreamSocket->read()
#1 /vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#2 /vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#3 /vendor/stefanak-michal/bolt/src/Bolt.php(274): Bolt\protocol\V4->pullAll()
#4 /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php(105): Bolt\Bolt->pullAll()
#5 /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php(54): Laudis\Neo4j\Bolt\BoltUnmanagedTransaction->runStatements()
#6 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(73): Laudis\Neo4j\Bolt\BoltUnmanagedTransaction->commit()
#7 /vendor/laudis/neo4j-php-client/src/Bolt/Ses in /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php on line 107
```
If I switch to http the error normally doesn't happen (which has been my workaround for some queries) but this time it is not working. 

I initially assumed there was some special character being mistranslated by the Bolt Driver but I have ruled that out by playing with my query.

**To Reproduce**
1. I can recreate this by performing my query on my system and I'm not sure I can figure out a way to recreate on other systems since it is unique to the way the query is built so I will just give a strange example.

This query fails using the driver but works directly in the NEO4J Browser:

```php
$query = "WITH {
	ownerId:'1',
	category:['Flagship','News & Politics'],
	search:'Donald Trump',
	wholeDensityWeight:10,
	partDensityWeight:5,
	distanceWeight:1,
	levenshteinWeight:1,
	jaroWinklerWeight:1,
	sorensenWeight:1,
	searchTerms:['Donald', 'Trump'],
	metaphones: ['TNLT','TRMP'],
	soundexes: ['D543','T651'],
	lowercases: ['donald','trump']
} AS vars
MATCH (o:Owner)
WHERE o.ownerId = vars.ownerId
WITH vars,o
MATCH (o)-[:OWNER_OF]->(c:Category)
WHERE  c.category in vars.category
WITH vars,c
MATCH (c)<-[:CATEGORY_OF]-(v:Video)<-[:SPEAKS_IN]-(:Speaker)-[:SPEAKS]->(:SpeechPart)<-[:SPOKEN_IN*3]-(sw0:SpokenWord)-[:PRECEDES*1..3]-(sw1:SpokenWord)
WHERE (
		sw0.metaphone in vars.metaphones 
		OR 
		sw0.soundex in vars.soundexes
		OR 
		sw0.lowercase in vars.lowercases
	)  AND  (
		sw1.metaphone in vars.metaphones 
		OR 
		sw1.soundex in vars.soundexes
		OR 
		sw1.lowercase in vars.lowercases
	)
	WITH
	{
		matchType:'transcript',
		assetId:v.assetId,
		searchTerm:vars.search,
		matchAgainst:COLLECT(DISTINCT [[sw0.word,sw0.wordIndex],[sw1.word,sw1.wordIndex]]),
		levenshteinDistance:(100 - toFloat(apoc.text.distance( sw0.word+' '+sw1.word,vars.search))/100*vars.distanceWeight),
		levenshteinSimilarity:(apoc.text.levenshteinSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.levenshteinWeight),
		jaroWinklerDistance:(apoc.text.jaroWinklerDistance( sw0.word+' '+sw1.word,vars.search)*vars.jaroWinklerWeight),
		sorensenDiceSimilarity:(apoc.text.sorensenDiceSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.sorensenWeight),
		wholeDensity:(toFloat(COUNT(sw0)+COUNT(sw1))/toFloat(v.wordCnt)*vars.wholeDensityWeight),
		partDensity:(0*vars.partDensityWeight),
		score:(
			((100 - toFloat(apoc.text.distance( sw0.word+' '+sw1.word,vars.search)))/100*vars.distanceWeight)+
			(apoc.text.levenshteinSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.levenshteinWeight)+
			(apoc.text.jaroWinklerDistance( sw0.word+' '+sw1.word,vars.search)*vars.jaroWinklerWeight)+
			(apoc.text.sorensenDiceSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.sorensenWeight)+
			(toFloat(COUNT(sw0)+COUNT(sw1))/toFloat(v.wordCnt)*vars.wholeDensityWeight)
		)/(
			vars.distanceWeight+
			vars.levenshteinWeight+
			vars.jaroWinklerWeight+
			vars.sorensenWeight+
			vars.wholeDensityWeight
		)
	} as rows1
RETURN DISTINCT rows1 LIMIT 10;
";
print_r( $this->conn->run($query) );
```

These next 2 queries work:
```php
$query = "WITH {
	ownerId:'1',
	category:['Flagship','News & Politics'],
	search:'Donald Trump',
	wholeDensityWeight:10,
	partDensityWeight:5,
	distanceWeight:1,
	levenshteinWeight:1,
	jaroWinklerWeight:1,
	sorensenWeight:1,
	searchTerms:['Donald', 'Trump'],
	metaphones: ['TNLT','TRMP'],
	soundexes: ['D543','T651'],
	lowercases: ['donald','trump']
} AS vars
MATCH (o:Owner)
WHERE o.ownerId = vars.ownerId
WITH vars,o
MATCH (o)-[:OWNER_OF]->(c:Category)
WHERE  c.category in vars.category
WITH vars,c
MATCH (c)<-[:CATEGORY_OF]-(v:Video)<-[:SPEAKS_IN]-(:Speaker)-[:SPEAKS]->(:SpeechPart)<-[:SPOKEN_IN*3]-(sw0:SpokenWord)-[:PRECEDES*1..3]-(sw1:SpokenWord)
WHERE (
		sw0.metaphone in vars.metaphones 
		OR 
		sw0.soundex in vars.soundexes
		OR 
		sw0.lowercase in vars.lowercases
	)  AND  (
		sw1.metaphone in vars.metaphones 
		OR 
		sw1.soundex in vars.soundexes
		OR 
		sw1.lowercase in vars.lowercases
	)
	WITH
	{
		matchType:'transcript',
		assetId:v.assetId,
		searchTerm:vars.search,
		matchAgainst:COLLECT(DISTINCT [[sw0.word,sw0.wordIndex],[sw1.word,sw1.wordIndex]]),
		levenshteinDistance:(100 - toFloat(apoc.text.distance( sw0.word+' '+sw1.word,vars.search))/100*vars.distanceWeight),
		levenshteinSimilarity:(apoc.text.levenshteinSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.levenshteinWeight),
		jaroWinklerDistance:(apoc.text.jaroWinklerDistance( sw0.word+' '+sw1.word,vars.search)*vars.jaroWinklerWeight),
		sorensenDiceSimilarity:(apoc.text.sorensenDiceSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.sorensenWeight),
		wholeDensity:(toFloat(COUNT(sw0)+COUNT(sw1))/toFloat(v.wordCnt)*vars.wholeDensityWeight),
		partDensity:(0*vars.partDensityWeight)
	} as rows1
RETURN DISTINCT rows1 LIMIT 10;
";
print_r( $this->conn->run($query) );
```

```php
$query = "WITH {
	ownerId:'1',
	category:['Flagship','News & Politics'],
	search:'Donald Trump',
	wholeDensityWeight:10,
	partDensityWeight:5,
	distanceWeight:1,
	levenshteinWeight:1,
	jaroWinklerWeight:1,
	sorensenWeight:1,
	searchTerms:['Donald', 'Trump'],
	metaphones: ['TNLT','TRMP'],
	soundexes: ['D543','T651'],
	lowercases: ['donald','trump']
} AS vars
MATCH (o:Owner)
WHERE o.ownerId = vars.ownerId
WITH vars,o
MATCH (o)-[:OWNER_OF]->(c:Category)
WHERE  c.category in vars.category
WITH vars,c
MATCH (c)<-[:CATEGORY_OF]-(v:Video)<-[:SPEAKS_IN]-(:Speaker)-[:SPEAKS]->(:SpeechPart)<-[:SPOKEN_IN*3]-(sw0:SpokenWord)-[:PRECEDES*1..3]-(sw1:SpokenWord)
WHERE (
		sw0.metaphone in vars.metaphones 
		OR 
		sw0.soundex in vars.soundexes
		OR 
		sw0.lowercase in vars.lowercases
	)  AND  (
		sw1.metaphone in vars.metaphones 
		OR 
		sw1.soundex in vars.soundexes
		OR 
		sw1.lowercase in vars.lowercases
	)
	WITH
	{
		score:(
			((100 - toFloat(apoc.text.distance( sw0.word+' '+sw1.word,vars.search)))/100*vars.distanceWeight)+
			(apoc.text.levenshteinSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.levenshteinWeight)+
			(apoc.text.jaroWinklerDistance( sw0.word+' '+sw1.word,vars.search)*vars.jaroWinklerWeight)+
			(apoc.text.sorensenDiceSimilarity( sw0.word+' '+sw1.word,vars.search)*vars.sorensenWeight)+
			(toFloat(COUNT(sw0)+COUNT(sw1))/toFloat(v.wordCnt)*vars.wholeDensityWeight)
		)/(
			vars.distanceWeight+
			vars.levenshteinWeight+
			vars.jaroWinklerWeight+
			vars.sorensenWeight+
			vars.wholeDensityWeight
		)
	} as rows1
RETURN DISTINCT rows1 LIMIT 10;
";
print_r( $this->conn->run($query) );
```

Notice that the only difference is in the last "WITH" portion Where I swapped half of the return.

**Expected behavior**
I was expecting to get the same data that the NEO4J Browser produces

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Library version: 2.0.4
 - Neo4j Version: 4.2.0
 - PHP version:  7.4.3
 - OS: Linux, Ubuntu

**Additional context**

**Comment by transistive** [comment]
Hi @jonathan-rowley,

Thank you for submitting this issue. I tried running it but could not reproduce the problem. I see you are using an older version of the driver. Can you update to the newest version (2.1.2) to check if it works there?

Kind regards,

Ghlen

**Comment by jonathan-rowley** [comment]
ah, yes. I did attempt to upgrade before but this time i gave it that specific version. I got an error and had to upgrade stefanak-michal/bolt package as well. Now I am on version 2.1.2 but I am still getting the error:

```
PHP Fatal error:  Uncaught Bolt\error\ConnectException: Read error in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:102
Stack trace:
#0 /vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(94): Bolt\connection\StreamSocket->read()
#1 /vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#2 /vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#3 /vendor/stefanak-michal/bolt/src/Bolt.php(277): Bolt\protocol\V4->pullAll()
#4 /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php(124): Bolt\Bolt->pullAll()
#5 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(76): Laudis\Neo4j\Bolt\BoltUnmanagedTransaction->runStatements()
#6 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(86): Laudis\Neo4j\Bolt\Session->runStatements()
#7 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(91): Laudis\Neo4j\ in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102

Fatal error: Uncaught Bolt\error\ConnectException: Read error in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:102
Stack trace:
#0 /vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(94): Bolt\connection\StreamSocket->read()
#1 /vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#2 /vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#3 /vendor/stefanak-michal/bolt/src/Bolt.php(277): Bolt\protocol\V4->pullAll()
#4 /vendor/laudis/neo4j-php-client/src/Bolt/BoltUnmanagedTransaction.php(124): Bolt\Bolt->pullAll()
#5 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(76): Laudis\Neo4j\Bolt\BoltUnmanagedTransaction->runStatements()
#6 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(86): Laudis\Neo4j\Bolt\Session->runStatements()
#7 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(91): Laudis\Neo4j\ in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102
```

However, it is now working with the http driver so i can go with that but i would like it to work with bolt as well.

**Comment by jonathan-rowley** [comment]
I was able to do some basic troubleshooting on my end and figured out that the DB is getting the query and executing it.

I ran htop on the DB server and when i sent the request i was able to watch the CPU's go crazy and when they stopped i got the error.

from there i looked at the exception:
```php
        try {
            return $this->conn->run($query,[],'bolt');
        } catch(Exception $e) {
            print_r($e);
            exit;
        }
```
the issue happened in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102:
```php
/**
     * Read from connection
     * @param int $length
     * @return string
     * @throws ConnectException
     */
    public function read(int $length = 2048): string
    {
        $res = stream_get_contents($this->stream, $length);
        if (empty($res))
            throw new ConnectException('Read error'); //<----- here

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```

This tells me that the DB is getting the request, executing it and when it is returned the read() function see's $res as empty

in other projects this means that the DB returned and error or something that was not in the correct format but when i run this query using http or on my neo4j browser it returns the data i need.

I am going to attempt to play around with it a bit and i'll report anything else i find.

**Comment by jonathan-rowley** [comment]
Very strange find:

I changed the code to do this:
```php
/**
     * Read from connection
     * @param int $length
     * @return string
     * @throws ConnectException
     */
    public function read(int $length = 2048): string
    {
        $res = stream_get_contents($this->stream, $length);
        if (empty($res)) // empty is what is throwing the error
        { fseek($this->stream, 0); // i thought maybe it needed to start at the beginning???
            $res = stream_get_contents($this->stream, $length);} // then i reran it

        if (empty($res))
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```

This worked and I got my response but it throws a warning now:
```bash
PHP Warning:  rewind(): stream does not support seeking in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102

Warning: rewind(): stream does not support seeking in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102
^C
ubuntu@ip-10-0-0-182:/tests$ php updateTermSearchNeo4j.php
PHP Warning:  fseek(): stream does not support seeking in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102

Warning: fseek(): stream does not support seeking in /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php on line 102

```

And I'm sure that it is not the best way to handle the issue.

I have found that somehow the stream is not starting at the beginning and may be off into the weeds when this stage is met. My problem is why this is not happening all of the time and how to create a better check for it.

**Comment by jonathan-rowley** [comment]
I was wrong about the reset (I think)

This is very confusing.

I took out the fseek and rewind and it worked.

```php
    // /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:92-112
    /**
     * Read from connection
     * @param int $length
     * @return string
     * @throws ConnectException
     */
    public function read(int $length = 2048): string
    {
        $res = stream_get_contents($this->stream, $length);// run the first time
        if (empty($res)) // if empty, why not? run it again
            $res = stream_get_contents($this->stream, $length); // it works this time

        if (empty($res)) // doesnt make it here since i ran it again.
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```

I have no idea why this is happening nor do i know why just running it again gets it to work. This cannot be the fix. it's a stupid fix. Does anyone have any other suggestions?

**Comment by jonathan-rowley** [comment]
Odd enough behavior to report:

I tried to replace stream_get_contents with fread and it behaves the exact same way.

first i tried this and it failed just like stream_get_contents:
```php
    // /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:92-112
    /**
     * Read from connection
     * @param int $length
     * @return string
     * @throws ConnectException
     */
    public function read(int $length = 2048): string
    {
        
        $res = fread($this->stream, $length); 

        if (empty($res)) // fails
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```
and then i tried this and  it worked like my last update:
```php
    // /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:92-112
    /**
     * Read from connection
     * @param int $length
     * @return string
     * @throws ConnectException
     */
    public function read(int $length = 2048): string
    {
        $res = fread($this->stream, $length);// try this first
        if (empty($res)) // if empty, why not? run it again
            $res = fread($this->stream, $length); // and then try this

        if (empty($res)) // i dont get it
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```
so now i put them both together and it works again:
```php
    // /vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:92-112
    /**
     * Read from connection
     * @param int $length
     * @return string
     * @throws ConnectException
     */
    public function read(int $length = 2048): string
    {
        $res = stream_get_contents($this->stream, $length);// try this first
        if (empty($res)) // if empty, why not? run it again
            $res = fread($this->stream, $length); // and then try this

        if (empty($res)) // here it would have to fail on both
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```

Turns out fread and stream_get_contents work the same so I think maybe it has something to do with the streaming connection which is using stream_socket_client().

Any ideas on what ive found? Is any of this helpful?

**Comment by jonathan-rowley** [comment]
Well, I have found the way to increase the timeout. I looked at the code and found that it is set when building the client.

I went ahead and made a merge request to the bolt driver with the correct error handling for timeouts and then I tested my code after increasing the timeout within the Laudis\Neo4j\ClientBuilder::create() function

it worked so i will now close this issue.

**Comment by transistive** [comment]
This is amazing work! Thank you for your perseverance! I am actually working on the documentation right now, so I will make sure the configuration options are explained as well

:+1:
