### ISSUE TITLE
Undefined index: $servers and $ttl in neo4j driver

### ISSUE THREAD

**Issue by jonathan-rowley** [neo4j-php/neo4j-php-client#84]
**Describe the bug**
I upgraded to version 2.1.2 and now the neo4j protocol doesn't work. I can use bolt or http directly but with neo4j i get an error:

```bash
PHP Notice:  Undefined index: servers in /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php on line 101

Notice: Undefined index: servers in /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php on line 101
PHP Notice:  Undefined index: ttl in /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php on line 101

Notice: Undefined index: ttl in /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php on line 101
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Laudis\Neo4j\Neo4j\RoutingTable::__construct() must be iterable, null given, called in /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php on line 122 and defined in /vendor/laudis/neo4j-php-client/src/Neo4j/RoutingTable.php:28
Stack trace:
#0 /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php(122): Laudis\Neo4j\Neo4j\RoutingTable->__construct()
#1 /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php(58): Laudis\Neo4j\Neo4j\Neo4jConnectionPool->routingTable()
#2 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(151): Laudis\Neo4j\Neo4j\Neo4jConnectionPool->acquire()
#3 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(136): Laudis\Neo4j\Bolt\Session->acquireConnection()
#4 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(76): Laudis\Neo4j\Bolt\Session->beginInstantTransaction()
#5 /vendor/lau in /vendor/laudis/neo4j-php-client/src/Neo4j/RoutingTable.php on line 28

Fatal error: Uncaught TypeError: Argument 1 passed to Laudis\Neo4j\Neo4j\RoutingTable::__construct() must be iterable, null given, called in /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php on line 122 and defined in /vendor/laudis/neo4j-php-client/src/Neo4j/RoutingTable.php:28
Stack trace:
#0 /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php(122): Laudis\Neo4j\Neo4j\RoutingTable->__construct()
#1 /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php(58): Laudis\Neo4j\Neo4j\Neo4jConnectionPool->routingTable()
#2 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(151): Laudis\Neo4j\Neo4j\Neo4jConnectionPool->acquire()
#3 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(136): Laudis\Neo4j\Bolt\Session->acquireConnection()
#4 /vendor/laudis/neo4j-php-client/src/Bolt/Session.php(76): Laudis\Neo4j\Bolt\Session->beginInstantTransaction()
#5 /vendor/lau in /vendor/laudis/neo4j-php-client/src/Neo4j/RoutingTable.php on line 28
```
The code is here:
```php
    /**
     * @param ConnectionInterface<Bolt> $driver
     *
     * @throws Exception
     */
    private function routingTable(ConnectionInterface $connection): RoutingTable
    {
        if ($this->table === null || $this->table->getTtl() < time()) {
            /** @var Bolt */
            $bolt = $connection->getImplementation();
            $protocol = $connection->getProtocol();
            if ($protocol->compare(ConnectionProtocol::BOLT_V43()) >= 0) {
                /** @var array{rt: array{servers: list<array{addresses: list<string>, role:string}>, ttl: int}} $route */
                $route = $bolt->route();
                ['servers' => $servers, 'ttl' => $ttl ] = $route['rt']; // <-- $servers and $ttl not defined before this point 
            } elseif ($protocol->compare(ConnectionProtocol::BOLT_V40()) >= 0) { // not sure what this is checking but it returns true in my case
                $bolt->run('CALL dbms.routing.getRoutingTable({context: []})');
                /**
                 * @var iterable<array{addresses: list<string>, role:string}> $servers
                 * @var int                       $ttl
                 */
                ['servers' => $servers, 'ttl' => $ttl] = $bolt->pullAll(); // <-- $servers and $ttl not defined before this point 
            } else {
                $bolt->run('CALL dbms.cluster.overview()');
                /** @var list<array{addresses: list<string>, role: string}> */
                $response = $bolt->pullAll();

                /** @var iterable<array{addresses: list<string>, role:string}> $servers */
                $servers = []; // <-- $servers first time being set 
                $ttl = time() + 3600;// <-- $ttl first time being set 
                foreach ($response as $server) {
                    $addresses = $server['addresses'];
                    $addresses = array_filter($addresses, static fn (string $x) => str_starts_with($x, 'bolt://'));
                    /**
                     * @psalm-suppress InvalidArrayAssignment
                     *
                     * @var array{addresses: list<string>, role:string}
                     */
                    $servers[] = ['addresses' => $addresses, 'role' => $server['role']];
                }
            }

            $this->table = new RoutingTable($servers, $ttl); // this is where the fatal error occurs since these variables are not set
        }

        return $this->table;
    }
```
It is an easy enough problem to fix but i dont know what the value of $servers or $ttl need to be.  If i knew that i could do a pull request and fix it myself which may bring me to another bug. who knows?
**To Reproduce**
I guess figure out how to make this true when establishing a connection and run it:
```php
($protocol->compare(ConnectionProtocol::BOLT_V40()) >= 0)
```
All i have to do to create it is run the neo4j driver.

**Expected behavior**
connection successful to the DB

**Desktop (please complete the following information):**
 - Library version: 2.1.2
 - Neo4j Version: 4.2.0
 - PHP version: 7.4.3
 - OS: Linux, Ubuntu

**Comment by jonathan-rowley** [comment]
ok, i learned about  setting array values into another array since PHP 7.1 (https://wiki.php.net/rfc/short_list_syntax) so I now have more knowledge in my toolbox but, It was not working correctly and the variables were never declared.

I tried to trace down what would cause the following to be true:
```php
($protocol->compare(ConnectionProtocol::BOLT_V40()) >= 0)
```
and i hit a dead end. From there I decided to see how the query inside of that conditional works against my DB.

I got this:
![image](https://user-images.githubusercontent.com/50716090/136288033-fbe3a024-28e8-402f-86c0-d6936daa107b.png)

and then i figured that it would pick up the keys and assign them correctly. 

it did not...

From there i wanted to see what this produced:
```php
$bolt->pullAll();
```
it did this:
```bash
Array
(
    [0] => Array
        (
            [0] => 300
            [1] => Array
                (
                    [0] => Array
                        (
                            [addresses] => Array
                                (
                                    [0] => {ip address}:7687
                                )

                            [role] => WRITE
                        )

                    [1] => Array
                        (
                            [addresses] => Array
                                (
                                    [0] => {ip address}:7687
                                    [1] => {ip address}:7687
                                )

                            [role] => READ
                        )

                    [2] => Array
                        (
                            [addresses] => Array
                                (
                                    [0] => {ip address}:7687
                                    [1] => {ip address}:7687
                                    [2] => {ip address}:7687
                                )

                            [role] => ROUTE
                        )

                )

        )

    [1] => Array
        (
            [bookmark] => {some weird looking key here}
            [type] => s
            [t_last] => 1
            [db] => {DB Name}
        )

)
```
I realized that the whole structure was all wrong.

I made some adjustments to the code and it worked:
changed this on file /vendor/laudis/neo4j-php-client/src/Neo4j/Neo4jConnectionPool.php
```php
/**
     * @param ConnectionInterface<Bolt> $driver
     *
     * @throws Exception
     */
    private function routingTable(ConnectionInterface $connection): RoutingTable
    {
        /** @var Bolt */
        $bolt = $connection->getImplementation();
        $protocol = $connection->getProtocol();
        if ($protocol->compare(ConnectionProtocol::BOLT_V43()) >= 0) {
            /** @var array{rt: array{servers: list<array{addresses: list<string>, role:string}>, ttl: int}} $route */
            $route = $bolt->route();
            ['servers' => $servers, 'ttl' => $ttl] = $route['rt'];
            $ttl += time();
        } elseif ($protocol->compare(ConnectionProtocol::BOLT_V40()) >= 0) {
            $bolt->run('CALL dbms.routing.getRoutingTable({context: []})');
            /**
             * @var iterable<array{addresses: list<string>, role:string}> $servers
             * @var int                       $ttl
             */
            ['servers' => $servers, 'ttl' => $ttl] = $bolt->pullAll();
            $ttl += time();
        } else {
            $bolt->run('CALL dbms.cluster.overview()');
            /** @var list<array{addresses: list<string>, role: string}> */
            $response = $bolt->pullAll();

            /** @var iterable<array{addresses: list<string>, role:string}> $servers */
            $servers = [];
            $ttl = time() + 3600;
            foreach ($response as $server) {
                $addresses = $server['addresses'];
                $addresses = array_filter($addresses, static fn (string $x) => str_starts_with($x, 'bolt://'));
                /**
                 * @psalm-suppress InvalidArrayAssignment
                 *
                 * @var array{addresses: list<string>, role:string}
                 */
                $servers[] = ['addresses' => $addresses, 'role' => $server['role']];
            }
        }

        return new RoutingTable($servers, $ttl);
    }
}
```
To this
```php
/**
     * @param ConnectionInterface<Bolt> $driver
     *
     * @throws Exception
     */
    private function routingTable(ConnectionInterface $connection): RoutingTable
    {
        if ($this->table === null || $this->table->getTtl() < time()) {
            /** @var Bolt */
            $bolt = $connection->getImplementation();
            $protocol = $connection->getProtocol();
            $servers = []; // moved this out of the conditional so it is always defined
            $ttl = time() + 3600; // moved this out of the conditional so it is always defined. still dont know why this is the default value
            if ($protocol->compare(ConnectionProtocol::BOLT_V43()) >= 0) {
                /** @var array{rt: array{servers: list<array{addresses: list<string>, role:string}>, ttl: int}} $route */
                $route = $bolt->route();
                ['servers' => $servers, 'ttl' => $ttl ] = $route['rt'];
            } elseif ($protocol->compare(ConnectionProtocol::BOLT_V40()) >= 0) {
                $bolt->run('CALL dbms.routing.getRoutingTable({context: []})');
                
                $response = $bolt->pullAll();

                $ttl = $response[0][0]; // i set this since it comes back from the server. no idea if this is correct
                foreach ($response[0][1] as $server) { // looping through the servers since the original keys were lost with pullAll() function
                    $servers[] = ['addresses' => $server['addresses'], 'role' => $server['role']]; // and then set the results
                }
            } else {
                $bolt->run('CALL dbms.cluster.overview()');
                /** @var list<array{addresses: list<string>, role: string}> */
                $response = $bolt->pullAll();

                /** @var iterable<array{addresses: list<string>, role:string}> $servers */
                foreach ($response as $server) {
                    $addresses = $server['addresses'];
                    $addresses = array_filter($addresses, static fn (string $x) => str_starts_with($x, 'bolt://'));
                    /**
                     * @psalm-suppress InvalidArrayAssignment
                     *
                     * @var array{addresses: list<string>, role:string}
                     */
                    $servers[] = ['addresses' => $addresses, 'role' => $server['role']];
                }
            }
            $this->table = new RoutingTable($servers, $ttl);
        }

        return $this->table;
    }
```

it now works as expected but i dont know how to troubleshoot the first conditional or if this is even correct for the rest of the code. 

if this looks good i can do a merge request. let me know.

**Comment by jonathan-rowley** [comment]
I see the pull request with the corrected code. thank you so much @transistive! I will close this bug now.
